### ISSUE TITLE
Check the plugin works with OpenMM 7.0

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#101]
OpenMM is about to release 7.0, we need to make sure the plugin still works.

If the 7.0 version is not yet in the main repo, it can be installed using:

    conda install -c omnia/label/pre openmm

If there is any build issue, open another ticket and then reference here, or create a pull request to fix it.

We can use the `OPENMM_MAJOR_VERSION` and `OPENMM_MINOR_VERSION` precompiler variables to adapt to incompatible APIs, see <https://github.com/paesanilab/mbpol_openmm_plugin/search?utf8=%E2%9C%93&q=OPENMM_MAJOR_VERSION>

**Comment by sqamara** [comment]
addressing here https://trello.com/c/cO40ada1/36-working-with-openmm-7-0

**Comment by sqamara** [comment]
https://github.com/paesanilab/mbpol_openmm_plugin/pull/106
