### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by nmardirossian** [paesanilab/mbpol_openmm_plugin#108]
Hi,

I am trying to compile MB-pol 1.0.2 and I get the following error:

[error.txt](https://github.com/paesanilab/mbpol_openmm_plugin/files/1023602/error.txt)

I have OpenMM 6.2, and I'm running on Ubuntu 16.04.2 (gcc 5.4.0)

I would appreciate any help to get this resolved!

Thank you.

**Comment by zonca** [comment]
Is there any reason​ you are not using conda?

That is the easiest way to get started.

https://anaconda.org/paesanilab/mbpol

From the error it looks it cannot find the openmm shared libraries, can you
check they are in the path?

**Comment by nmardirossian** [comment]
OK thank you for the suggestion. I installed it through conda and it's working.

Thank you!
