### ISSUE TITLE
Performance issues on Reference Platform 3-body on 256 water molecules

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#110]
one step takes 30 seconds

dataset of 256 molecules in `pdb/TIP5P_PIMC_0C_LIQ.0.pdb`
number of triplets is: 242752

**Comment by zonca** [comment]
@chemphys can you easily extract what should be the number of triplets in this dataset from another code? see above

**Comment by chemphys** [comment]
Which is the cutoff you use for the triplets? The value in the polynomials, 4.5 Angstrom?

**Comment by zonca** [comment]
Yes

Il lun 9 ott 2017, 21:22 Marc Riera Riambau <notifications@github.com> ha
scritto:

**Comment by chemphys** [comment]
Can you point me to where the pdb is?

**Comment by zonca** [comment]
https://github.com/paesanilab/mbpol_openmm_qmc_comparison/blob/master/openmm_mbpol/pdb/TIP5P_PIMC_0C_LIQ.0.pdb

**Comment by zonca** [comment]
it is a periodic box of size: 19.3996888399961804 A

I counted triplets with `mdtraj` and I get: 1967

**Comment by chemphys** [comment]
Is there any way that you can deactivate PBC? Because my code does not have the PBC implemented. Maybe you can increase the box size 20 Angstrom in all the directions. Then we will have a 1 to 1 comparison.

**Comment by zonca** [comment]
It's fine, useful even if you don't have PBC

**Comment by fpaesani** [comment]
I think that OpenMM can also do calculations without PBC. @zonca, is what we called "cluster calculations". I am pretty sure we did those comparisons with Greg when we were implementing MB-pol in OpenMM.

**Comment by zonca** [comment]
@fpaesani yes, it can, we will compare all 3 software tools  (openmm, mdtraj, @chemphys' code) with and without PBC

**Comment by chemphys** [comment]
Without pbc i get 3865 trimers. Can you put the 3b energy you get?

**Comment by zonca** [comment]
I found a bug with the cutoff, the global nonbondedCutoff was applied also to 3body, this creates a huge neighborlist (Energy is still correct because another cutoff is inside the evaluation code): 

With correct cutoff, OpenMM: 1473 Cluster, 2344 PME
`mdtraj`: 1473 Cluster, 1967 PME

Cluster energy just 3body: 44.72 kcal/mol

**Comment by chemphys** [comment]
Can we do the test with something relatively smaller? I don't get the same numbers (3865 trimers and 45.4899kcal/mol energy 3b only). I cannot go through something that big. Can you confirm that the cutoff is 4.5 angstrom? Also, how are you screening the trimers? A trimer energy is 0 if 2 of the 3 O-O distances are more than 4.5 ( @fpaesani , that's how it works right?)

**Comment by zonca** [comment]
yes, I confirmed above, it is 4.5A.

In the plugin the screening is different. a triplet needs to have all 3 distances below 4.5A.

**Comment by chemphys** [comment]
But then that is not correct. @fpaesani , correct me if I am wrong, but as far as I understand, and for how the switch works, if two of the distances is not 0, there should be a 3b energy. Lets say we have a water centerd with O at (0, 0, 0). A second water is at (0, 0, 2.5) and a third water is at (0,0,5). Water 1 and water 3 are farther than 4.5, but the polynomials won't return 0.
Am I correct? Or I am missunderstanding it?

**Comment by fpaesani** [comment]
@chemphys is correct. The 3B still exists if only one distance is below 4.5A. Please see the definition of 3B switching function in the original paper.

**Comment by chemphys** [comment]
@zonca can you recalculate 3B and number of trimers changing the criteria?

**Comment by zonca** [comment]
is there a limit on the other distances? or we loop through all the other possible molecules in the box?

**Comment by zonca** [comment]
performance issue on 3b is fixed, 1 step is now 0.352513 instead of 30 seconds. Fix implemented in #111.

Now investigating Electrostatics. I'll open another issue about 3B screening.

**Comment by chemphys** [comment]
What I do in my algorithm is the following:
```
for i in all_molecules:
  find all molecules that are within R < 4.5
  for j in all_matches
    find all molecules k that are within 4.5 of molecule j
    add trimer i,j,k
  end do
end do
```

**Comment by chemphys** [comment]
@zonca , when you say "now requires all 3 distances to be below 4.5A, instead just 2 of them are necessary, the 3rd could be higher", you mean that now is in the way that doesn't force all 3 distances to be less than 4.5?

**Comment by chemphys** [comment]
And can you recalculate trimers and 3b energy?

**Comment by zonca** [comment]
no, work on electrostatics is higher priority, I'll do that later, see #112

**Comment by chemphys** [comment]
ok

**Comment by zonca** [comment]
@chemphys how are you removing duplicates after you run this?

**Comment by chemphys** [comment]
[Here](https://github.com/paesanilab/clusters_ultimate/blob/master/src/bblock/system.cpp#L107) I perform that. I just assure that index i > j > k for a triplet <i,j,k>

**Comment by zonca** [comment]
performance is now acceptable, l'll focus on Electrostatics now and check everything together after that.
