### ISSUE TITLE
Fix 3-body neighbor list implementation

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#112]
Fix 3-body neighborlist implementation, it now requires all 3 distances to be below 4.5A, instead just 2 of them are necessary, the 3rd could be higher (worst case it could be 9A if 3 molecules are aligned.

@chemphys @fpaesani please provide feedback if any of the above is not correct

see previous discussion in #110

**Comment by zonca** [comment]
`mdtraj` result with this new algorithm on https://github.com/paesanilab/mbpol_openmm_qmc_comparison/blob/master/openmm_mbpol/pdb/TIP5P_PIMC_0C_LIQ.0.pdb

* PBC: 5533
* Cluster: 3865

The number for cluster is the same @chemphys gets https://github.com/paesanilab/mbpol_openmm_plugin/issues/110#issuecomment-335526573

**Comment by zonca** [comment]
this should be fixed soon in #111, followup there

**Comment by zonca** [comment]
@agoetz @fpaesani this modification of the 3body list changed a little bit the energy because I was missing some triplets before.

Should I rerun the comparison with QMC I did a while ago? Results are at: https://github.com/paesanilab/mbpol_openmm_qmc_comparison

It is probably going to take one full day of work (a week for me).

**Comment by agoetz** [comment]
@fpaesani Are we using this comparison for anything? It seems like a very inefficient way for testing correctness of an implementation.

@zonca Comparing energy (and gradients) for a single or at most a few snapshots should be sufficient.

**Comment by fpaesani** [comment]
@agoetz @zonca I don't think we are using it for any actual comparison. I believe that it was used by Greg and Andrea initially when they worked on the first implementation of MB-pol in OpenMM.

**Comment by zonca** [comment]
ok
