### ISSUE TITLE
Performance issues in Electrostatics

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#113]
on 256 water molecules, everything in Reference platform

* AMOEBA takes 4 seconds with no Cutoff, 2 seconds with PME.
* OpenMM-MBPol takes about 30s just Electrostatics for 1 step

**Comment by zonca** [comment]
Identified the bottleneck, it is the `getAndScaleInverseRs` function, see https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/platforms/reference/src/MBPolReferenceElectrostaticsForce.cpp#L255

This function is not present in AMOEBA, in MBPol it adjusts the scaling factors based on the type of interaction.
Replacing this with a dummy function, 1 step takes 1.5s.

@fpaesani @agoetz @chemphys I wonder if you already have any suggestion on how to speed this up.

Otherwise next week I'll investigate if I can precompute all the needed scaling factors in a sort of table/dictionary and then index into that inside the loops.

**Comment by chemphys** [comment]
I am looking at this. I will let you know if I have something faster...

**Comment by darcykimball** [comment]
Out of curiosity, which paper (if any) specifies the scaling behavior? Also, as a ghetto hack: if `getAndScaleInverseRs` is a pure function, would memoizing speed it up by much? I imagine it's less work than refactoring this stuff all out, but of course it'll have to build and store N^2 entries at runtime. Further: is the slowdown due to branching or number crunching?

**Comment by zonca** [comment]
Calls:

In `calculateElectrostaticPairIxn`  for cluster and `calculatePmeDirectElectrostaticPairIxn` for PME, all with same `r`:

```
    RealOpenMM scale1CC =getAndScaleInverseRs(particleI,particleJ,r,true,1,TCC);
    RealOpenMM scale3CD =getAndScaleInverseRs(particleI,particleJ,r,true,3,TCD);
    RealOpenMM scale3CC =getAndScaleInverseRs(particleI,particleJ,r,true,3,TCC);
    RealOpenMM scale5CD =getAndScaleInverseRs(particleI,particleJ,r,true,5,TCD);
    RealOpenMM scale5DD =getAndScaleInverseRs(particleI,particleJ,r,true,5,TDD);
    RealOpenMM scale7DD =getAndScaleInverseRs(particleI,particleJ,r,true,7,TDD);
```

in `calculateInducedDipolePairIxns`:

```
    RealOpenMM scale3 = getAndScaleInverseRs( particleI, particleJ, r, false, 3, TDD);
    RealOpenMM scale5 = getAndScaleInverseRs( particleI, particleJ, r, false, 5, TDD);
```

I'll start from the second one, it is in the inner loop of dipole estimation and doesn't change for each pair of particles.

There there are also 4 calls in the charge redistribution.

**Comment by chemphys** [comment]
Hey @zonca ,

I implemented electrostatics in my new software. Without calculating gradients, it takes 1.7 seconds for 256 water molecules. With gradients it will be at most twice that amount.

**Comment by zonca** [comment]
Good, can you please point me to the code?

Il ven 27 ott 2017, 02:02 Marc Riera Riambau <notifications@github.com> ha
scritto:

**Comment by chemphys** [comment]
You can find it [here](https://github.com/chemphys/clusters_ultimate/blob/mrr/add_electrostatics/src/potential/electrostatics/electrostatics.cpp)
I will work on the gradient implementation now, and probably work with daniel to make it even faster. It was compiled with icpc using optimizations.
See you!

Marc

**Comment by chemphys** [comment]
So, I updated the function. With gradients, it takes 2.28 seconds.
I will fix a couple performance issues, and it will probably be even faster.

**Comment by zonca** [comment]
implemented precomputation of all the scale factors in the induced dipole loop, precomputation takes 0.37s, loop time decreased from 18.81s to 1.1s.

Now total is 8s. I'll check the other calls to the function.

**Comment by zonca** [comment]
Precomputed a call to `ttm::gammln` and created specialized function to compute at the same time order 1 and 3 used in the contribution from other atoms in same water, now 6.3s.

**Comment by zonca** [comment]
For now 6.3s is good enough compared to 4s of AMOEBA.
Now some tests are segfaulting, I'll debug that and then merge the code.

**Comment by chemphys** [comment]
@zonca , the time is for the entire calculation or just electrostatics?

**Comment by zonca** [comment]
Electrostatics


Il ven 3 nov 2017, 17:14 Marc Riera Riambau <notifications@github.com> ha
scritto:

**Comment by zonca** [comment]
Electrostatics


Il ven 3 nov 2017, 17:16 Andrea Zonca <zonca@sdsc.edu> ha scritto:

**Comment by chemphys** [comment]
Are you using optimizations when compiling the code?

**Comment by zonca** [comment]
finalized this.

Next I'll merge the 3b fix and then I'll create a pull request for this with 1 single commit.

**Comment by zonca** [comment]
I posted the benchmarks on the wiki at: https://github.com/paesanilab/mbpol_openmm_plugin/wiki/Benchmarks-MBpol 

in #114 I also added the updated benchmark script and the 2 input PDB files

**Comment by zonca** [comment]
ok, performance is good enough for now, next step will be to implement the CPU platform with threading support.
