### ISSUE TITLE
nonbondedCutoff typo

### ISSUE THREAD

**Issue by semodi** [paesanilab/mbpol_openmm_plugin#117]
``` nonBondedCutoff ``` should be ``` nonbondedCutoff ```:

https://github.com/paesanilab/mbpol_openmm_plugin/blob/1259308c25ae6b2979d4b7f518c3aa71523e0a82/python/water14.py#L36

and the same in 
https://github.com/paesanilab/mbpol_openmm_plugin/blob/1259308c25ae6b2979d4b7f518c3aa71523e0a82/python/water14.ipynb

What is weird is that OpenMM does not throw an exception but rather simply ignores it. This creates issues for calculations with PME if the box size is smaller than half the default Electrostatic cutoff (even though the users would think that they have specified a valid cutoff distance).

The typo is easily fixed but the fact that no exception is thrown is a bit worrisome in my opinion.

**Comment by zonca** [comment]
thanks for the fix!
