### ISSUE TITLE
Error reading a PDB file

### ISSUE THREAD

**Issue by snpreddy** [paesanilab/mbpol_openmm_plugin#122]
Dear All,

I have observed in the pdb files (water14_cluster.pdb, water256_bulk.pdb), atoms labeled as M, what it represents and how assigned the values of M in case of water14_cluster.pdb. At the end of water14_cluster.pdb, ENDMDL is observed and missing in the water256_bulk.pdb. What is the specific format of a pdb file?

I have checked the simulations with the examples of water14 and water256_bulk, and both are working fine. When I changed my system from water14 to water trimer, it is terminating by the below error. Just changed the pdb file and then ran the mbpol_builder to generate python code. While running the python code, I got the error.

Traceback (most recent call last):
  File "build.py", line 17, in <module>
    pdb = mm.app.PDBFile("w3.pdb")
  File "/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/simtk/openmm/app/pdbfile.py", line 95, in __init__
    pdb = PdbStructure(inputfile, load_all_models=True, extraParticleIdentifier=extraParticleIdentifier)
  File "/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 152, in __init__
    self._load(input_stream)
  File "/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 163, in _load
    self._add_atom(Atom(pdb_line, self, self.extraParticleIdentifier))
  File "/opt/conda/miniconda2/envs/openmm_env/lib/python3.6/site-packages/simtk/openmm/app/internal/pdbstructure.py", line 781, in __init__
    y = float(pdb_line[38:46])
ValueError: could not convert string to float: '10    1.'

I will be thankful if any suggestions to resolve the problem
Thank you
Nagaprasad

**Comment by zonca** [comment]
PDB is a standard format, please look for documentation online.

M is a virtual site computed as a weighted mean of the H and O positions.


Please upload the pdb that fails to gist.github.com and link it here.

**Comment by snpreddy** [comment]
Link for pdb file.

https://gist.githubusercontent.com/snpreddy/7b91a9cdadff236fa76ee8a290a8a4e2/raw/527e9d02e3226e8a9681b874a90100fb328bac9b/w3.pdb

By the way, how can I assign the weighted mean values? Can I keep them as 0.00 like bulk water example?

**Comment by zonca** [comment]
you cannot have all those decimals in a PDB, it is fixed length, use this one as an example and replace the numbers:

https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/water3.pdb

yes, you can set them to zero, they are automatically computed by OpenMM anyway.

**Comment by snpreddy** [comment]
Thank you, it is working fine with fixed lengths. 
How can I restart a terminated MD job?

Thanks
Naga

**Comment by zonca** [comment]
about restarting I don't think it is supported, look at the OpenMM documentation for more information: http://docs.openmm.org/latest/userguide/index.html
