### ISSUE TITLE
NVT followed by NVE

### ISSUE THREAD

**Issue by snpreddy** [paesanilab/mbpol_openmm_plugin#124]
Dear All,

I have seen the *.ini files, and I didn't find any one which NVT followed by NVE. Could you please some one help me, where can I find?

Thanks in advance
Naga

**Comment by zonca** [comment]
`mbpol_builder` (that reads the .ini) is just a quick way to get started, more complicated simulations need to be written in Python,
see here an example of running NVT and then NVE: https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/example_nvt_nve.py

**Comment by snpreddy** [comment]
Hi,
Sorry for bothering you, I have found that one and tried to do some modifications. I want to save the position file and modified the code. It's writing log files, and trajectory file, in nve log file the number of lines are twice of production steps. If I remove the lines from code (from try: ...to end) the log files having correct number of lines. In both cases with and with out writing trajectory the log files also not same. Could you please have a look what's going wrong?

[w2-without_nvt.log](https://github.com/paesanilab/mbpol_openmm_plugin/files/2020666/w2-without_nvt.log)
[w2-without_nve.log](https://github.com/paesanilab/mbpol_openmm_plugin/files/2020667/w2-without_nve.log)
[w2-with_nvt.log](https://github.com/paesanilab/mbpol_openmm_plugin/files/2020668/w2-with_nvt.log)
[w2-with_nve.log](https://github.com/paesanilab/mbpol_openmm_plugin/files/2020669/w2-with_nve.log)
https://gist.github.com/snpreddy/7e57a0424673116043e1e1acd196c079


Thanks
Naga

**Comment by zonca** [comment]
I think there is a mistake in the script, you are calling the production simulation twice, at line 69 and 83.

* https://gist.github.com/snpreddy/7e57a0424673116043e1e1acd196c079#file-with_traj-py-L69
* https://gist.github.com/snpreddy/7e57a0424673116043e1e1acd196c079#file-with_traj-py-L83

**Comment by snpreddy** [comment]
Thank you very much.

I have corrected it, and the log files are not same with and with out writing the trajectory file.
you can check it for the example python file https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/example_nvt_nve.py

It writes only log files and no trajectory files. If we add a line to write production trajectory, the log files should be same, but log files are not same. 
Just I am adding a line  "simulation.reporters.append(app.PDBReporter('trajectory.pdb', 1))" before the last three lines (before the line of "print('Running Production...')"). 

I have a doubt whether I am doing anything wrong? Because, I have found the water dimer is dissociating as fragments. Please let me know if anything is missing.

Thank you
Naga
