### ISSUE TITLE
Problem with NVE in water pentamer

### ISSUE THREAD

**Issue by snpreddy** [paesanilab/mbpol_openmm_plugin#125]
Hi,
I am trying some test jobs of water clusters. Already intimated the problem of evaporating water molecules (breaking hydrogen bonds at low T (around 200K)). A strange problem observed in case of water pentamer. I am trying NVT followed by NVE at 50K, through out the NVT trajectory, pentamer is cyclic and average T also around 50K. Ones it goes NVE the T is increasing and reaching around 200K, Breaking HBs and one water is going away from the ring. I am wondering, 200 K is too small to evaporate water. I am unable to find what's going wrong. Please let me know if anything wrong in the code and the simulations.  taking 0.2 fs as time step, and given the Conserved quanties of E and T, initial and broken structures.

[temp.pdf](https://github.com/paesanilab/mbpol_openmm_plugin/files/2034255/temp.pdf)
https://gist.github.com/snpreddy/728514d999b209a221d60ed2fb3b6f4d

Thank you
Naga

**Comment by zonca** [comment]
Your water molecules do not have virtual sites (M)

**Comment by snpreddy** [comment]
Virtual sites was there, just I removed those lines for visual compatibility.

**Comment by zonca** [comment]
I don't see anything wrong in the software, @agoetz could you please take a look?

**Comment by snpreddy** [comment]
Here I am copying the last NVT step trajectory data, while analyzing the results, I removed M sites from the NVE trajectory file, so the problem is not related with M. Please let me know

Thanks
Naga

MODEL     500000
HETATM    1  O   HOH A   1      -1.776   1.533  -0.523  1.00  0.00           O
HETATM    2  H1  HOH A   1      -2.691   1.743  -0.373  1.00  0.00           H
HETATM    3  H2  HOH A   1      -1.733   0.676  -0.973  1.00  0.00           H
HETATM    4  M   HOH A   1      -1.962   1.395  -0.587  1.00  0.00
HETATM    5  O   HOH A   2       0.225   1.642   1.296  1.00  0.00           O
HETATM    6  H1  HOH A   2       0.579   2.512   1.126  1.00  0.00           H
HETATM    7  H2  HOH A   2      -0.557   1.579   0.723  1.00  0.00           H
HETATM    8  M   HOH A   2       0.134   1.814   1.137  1.00  0.00
HETATM    9  O   HOH A   3       1.156  -1.662  -0.699  1.00  0.00           O
HETATM   10  H1  HOH A   3       1.324  -1.438   0.236  1.00  0.00           H
HETATM   11  H2  HOH A   3       1.911  -1.263  -1.147  1.00  0.00           H
HETATM   12  M   HOH A   3       1.353  -1.529  -0.595  1.00  0.00
HETATM   13  O   HOH A   4      -1.218  -0.836  -1.865  1.00  0.00           O
HETATM   14  H1  HOH A   4      -0.429  -1.248  -1.446  1.00  0.00           H
HETATM   15  H2  HOH A   4      -1.725  -1.564  -2.216  1.00  0.00           H
HETATM   16  M   HOH A   4      -1.158  -1.079  -1.850  1.00  0.00
HETATM   17  O   HOH A   5       1.643  -0.622   1.806  1.00  0.00           O
HETATM   18  H1  HOH A   5       1.733  -0.759   2.751  1.00  0.00           H
HETATM   19  H2  HOH A   5       1.218   0.251   1.686  1.00  0.00           H
HETATM   20  M   HOH A   5       1.572  -0.465   1.982  1.00  0.00
TER      21      HOH A   5
ENDMDL
END
