### ISSUE TITLE
Thermostat 

### ISSUE THREAD

**Issue by snpreddy** [paesanilab/mbpol_openmm_plugin#126]
Hi,

I am running simulations with Andersen Thermostat, I want to use Nose-Hoover Thermostat in the NVT study, and didn't find it. I will be grateful if some one provide details.

Thanks
Naga

**Comment by chemphys** [comment]
For this you should look at the OpenMM user manual. This repository is simply the implementation of MB-pol in OpenMM. Any simulations details/problems should be addressed in the OpenMM forum.

There is an [issue](https://github.com/pandegroup/openmm/issues/1306) in OpenMM issues  that might answer your question. Seems that at least, two years ago, this was not implemented, but there is a similar version.

Hope this helps!

**Comment by snpreddy** [comment]
Thanks for your reply. I have crossed the post and the openmm manual too. I didn't find the implementation. That's why I posted to get some help from developers.

Thanks

**Comment by zonca** [comment]
you can take a look at `openmmtools` http://openmmtools.readthedocs.io/en/latest/integrators.html

or ask on the OpenMM forum: https://simtk.org/plugins/phpBB/indexPhpbb.php?f=161
