### ISSUE TITLE
Problem in writing Velocities file

### ISSUE THREAD

**Issue by snpreddy** [paesanilab/mbpol_openmm_plugin#127]
Hi,
I have couple of problems
1) Velocities are not writing in the NETCDF binary file, even having ParmEd Python package. Could you please let me know whether we need to link it some where?

2) Same python code giving different results in different run:
A test job, NVT followed by NVE gave log files and PDB file. When I run the same job again, the log files and PDB files are not same as older run and varying a lot. How is it possible?

https://gist.github.com/snpreddy/081f23cdefd14074e1045a28777185bd

Thanks
Naga

**Comment by zonca** [comment]
Hi,
This issues has nothing to do with MBPol, please look for OpenMM support.
