### ISSUE TITLE
Energy not conserved in NVE

### ISSUE THREAD

**Issue by snpreddy** [paesanilab/mbpol_openmm_plugin#128]
Hi,
I made another trial NVT followed by NVE with tetramer, in NVT, I ran 0.5 ns, Energy and temperature are conserved. In NVE, energy is not conserved. I am using 0.2 fs time step and running 0.5 ns from the end of NVT state. 

1) I would like to know whether 0.2 fs time step is reasonable? In general, which time step is good for small water clusters? or any thing missing in my python code?

2) Maximum available forces are three body, is the problem due to missing higher body terms? How much accurate if I go with large water clusters like water 21mer?

3) How accurate the code for water trimer? I think, 3 body terms are enough, to give accurate results in case of trimer.

https://gist.github.com/snpreddy/5d7eaa1cf5a467f1809660c06e4a77ca
[w4.pdf](https://github.com/paesanilab/mbpol_openmm_plugin/files/2079533/w4.pdf)

Thanks
Naga

**Comment by chemphys** [comment]
As a side note, did you realize that you are using:
```
system = forcefield.createSystem(pdb.topology, nonbondedMethod=nonbonded,
    nonbondedCutoff=0.9*unit.nanometers, ewaldErrorTolerance=ewaldErrorTolerance)
```
Can you try to follow the [example for a 14 water cluster](https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/water14.py) and see if that fixes the problem? 

Regarding your questions, all of them are answered [here](https://pubs.acs.org/doi/abs/10.1021/ct400696d), [here](https://pubs.acs.org/doi/abs/10.1021/ct400863t), [here](https://pubs.acs.org/doi/abs/10.1021/ct500079y), and [here](https://pubs.acs.org/doi/abs/10.1021/ct5004115)

I recommend a deep reading of these papers before you proceed with any simulation.

This issues should be regarding bugs with the MB-pol implementation in OpenMM. If a simulation is not working, please make sure that you have the proper set up for clusters or bulk. In your case, I think the `system = forcefield...` is not correctly defined for your system.

**Comment by chemphys** [comment]
Because that is a single point calculation. As stated in the papers, to run a full MD simulation, the time step should be 0.2 fs. And also, please use a larger cutoff than 9 angstrom for the non bonded interactions. In the example, it is set to 1E+03, but if you use a box, set it to half of the box maximum.
Hopefully this fixes the problems you have!

**Comment by snpreddy** [comment]
Dear @chemphys, I have tried the cutoff 1e3, and still the energy is not conserved, I don't know what's going wrong. I will be happy, if some one suggest any hint.

Thanks
Naga

**Comment by chemphys** [comment]
For a cluster simulation, and for a system as small as this one, the kinetic fluctuations might be too large.
1. Try a larger system
2. Try a lower T (10K)


Get Outlook for Android<https://aka.ms/ghei36>

________________________________
