### ISSUE TITLE
Local energy minimization 

### ISSUE THREAD

**Issue by maxentile** [paesanilab/mbpol_openmm_plugin#132]
Hello!

I'm getting started with using MB-pol on the 14-water cluster in this example https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/python/water14.py and I noticed some surprising behavior.

If I call the `LocalEnergyMinimizer`, then the potential energy decreases to approximately -1e+11 kcal/mol, and velocity verlet is unstable from this local minimum even with a step size of 1e-5 fs (with potential energy fluctuating to as low as -1e+16 kcal/mol before "exploding" to a large positive value).
![potential_energy_trace](https://user-images.githubusercontent.com/5759036/70676603-bf47a780-1c5a-11ea-8a0e-afa87c6d7c58.png)

However, all is well if I comment out the local energy minimization step, and the potential energy happily fluctuates around -60-80 kcal/mol.

![potential_energy_trace_no_minimization](https://user-images.githubusercontent.com/5759036/70676611-c2429800-1c5a-11ea-9a99-ad77ed9f5fd2.png)

Are there special considerations / precautions when energy-minimizing with this model? (e.g. do the virtual sites need to be handled in a nonstandard way?)

Steps required to reproduce:
* Installed from binary as instructed here: https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/INSTALL.md#how-to-install-the-binary-distribution-for-gnulinux-64bit-with-conda
* Cloned the mbpol_openmm_plugin repository, executed these two scripts https://gist.github.com/maxentile/e1220e5c5d38c0dff28fc543ff39e6c1 from the folder https://github.com/paesanilab/mbpol_openmm_plugin/tree/master/python

Related Issue: https://github.com/paesanilab/mbpol_openmm_plugin/issues/20

Best regards,
Josh

**Comment by fpaesani** [comment]
Hi Josh,

Thank you for your interest in MB-pol. There shouldn't be any specific precautions to take but it is also true that our implementation of MB-pol in OpenMM is obsolete and we don't have any control on OpenMM. 

We have developed an independent C++ library (MBX) that, in principle, can be interfaced to any MD or MC driver. You can find the initial version here: http://paesanigroup.ucsd.edu/software/mbx.html. We are going to update it this week and, therefore, I would suggest to wait Monday to download it. I can email you when we are done with the updates.

We also provide an interface with i-PI, a generic MD driver, that can be used for both optimizations and MD simulations. At the moment, MBX combined with i-PI for is the best way to use MB-pol. We are working on an interface with LAMMPS which we hope to release early next year.

All the best,
Francesco

**Comment by maxentile** [comment]
Thank you Francesco for these helpful pointers and comments! I will keep an eye out for next update of MBX.

Many thanks,
Josh
