### ISSUE TITLE
Check each component of Electrostatics PME forces against the error

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#40]
Run the unit test of 1 water molecule and check each component of the PME forces.

**Comment by zonca** [comment]
I am testing with just 1 water molecule, the first molecule of the usual `water3` system.

I am testing with polarizability set to 0 and a box size of 18A, atom order is `OHHM`.

**No charge redistribution**

In this case finite differences agree with our estimate of the forces:

```cpp
Force atom 0: [-0.0123682, 0.019561, -0.0290194] Kcal/mol/A <openmm-mbpol>
Force atom 0: [-0.0123682, 0.019561, -0.0290194] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 1: [0.00637406, -0.0100907, 0.0143082] Kcal/mol/A <openmm-mbpol>
Force atom 1: [0.00637406, -0.0100907, 0.0143082] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 2: [0.00653297, -0.00983631, 0.0150221] Kcal/mol/A <openmm-mbpol>
Force atom 2: [0.00653297, -0.00983631, 0.0150221] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 3: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>
```

**Comment by zonca** [comment]
**With charge redistribution**

```cpp
Force atom 0: [-52.2738, 89.5023, -134.833] Kcal/mol/A <openmm-mbpol>
Force atom 0: [-0.0102713, 0.0168557, -0.0252335] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 1: [63.3457, -48.5356, 47.5684] Kcal/mol/A <openmm-mbpol>
Force atom 1: [-0.000491702, -0.00838144, 0.0143935] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 2: [-11.07, -40.9672, 87.2642] Kcal/mol/A <openmm-mbpol>
Force atom 2: [0.0126705, -0.00890535, 0.0102875] Kcal/mol/A <openmm-mbpol finite differences>

Force atom 3: [0, 0, 0] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0, -0, -0] Kcal/mol/A <openmm-mbpol finite differences>
```

Where is this large bias coming from?

1) checking the forces before `OpenMM` redistributes them from `M` site to `OHH`:

```cpp
Force atom 0: [-52.2545, 89.4703, -134.785] Kcal/mol/A <openmm-mbpol>
Force atom 1: [63.3529, -48.5475, 47.5863] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-11.0629, -40.9791, 87.2821] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0.0336263, 0.0559141, -0.0837911] Kcal/mol/A <openmm-mbpol>
```

issue is already present

**Comment by zonca** [comment]
2) Forces after Direct Space computation
```cpp
Force atom 0: [-50.5026, 86.5496, -130.419] Kcal/mol/A <openmm-mbpol>
Force atom 1: [61.7922, -47.5442, 46.7884] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-10.5425, -40.2029, 85.3996] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0.747199, 1.1975, -1.76911] Kcal/mol/A <openmm-mbpol>
```

It looks like the error is already present in direct space.

3) Forces after Reciprocal Space Induced
```cpp
Force atom 0: [-50.5026, 86.5496, -130.419] Kcal/mol/A <openmm-mbpol>
Force atom 1: [61.7922, -47.5442, 46.7884] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-10.5425, -40.2029, 85.3996] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0.747199, 1.1975, -1.76911] Kcal/mol/A <openmm-mbpol>
```
As expected there is no contribution, we set polarizability to zero.

4) Forces after Reciprocal Space Fixed
```cpp
Force atom 0: [-52.2545, 89.4703, -134.785] Kcal/mol/A <openmm-mbpol>
Force atom 1: [63.3529, -48.5475, 47.5863] Kcal/mol/A <openmm-mbpol>
Force atom 2: [-11.0629, -40.9791, 87.2821] Kcal/mol/A <openmm-mbpol>
Force atom 3: [-0.0336263, 0.0559141, -0.0837911] Kcal/mol/A <openmm-mbpol>
```

**Comment by zonca** [comment]
**Investigating direct space interaction**

```cpp
x component of force on Oxygen from charge redistribution interaction with atom 1: -13.5774 Kcal/mol/A 
x component of force on Oxygen from charge redistribution interaction with atom 2: -3.69797 Kcal/mol/A 
x component of force on Oxygen from charge redistribution interaction with atom 3: -33.2271 Kcal/mol/A 
```

**Comment by zonca** [comment]
Let's focus on the largest of these contributions, `O`-`M`, the first component is the charge derivative with respect to `H1`:

    ftm21 +=  (rr1I_ewald + rr1I_screen - rr1I) * particleI.chargeDerivatives[s][0] * particleJ.charge; // charge - charge

* Force is `26.98 Kcal/mol/A `
* `rr1I_ewald = 8.6`
* `rr1I = 11.67`
* chargeDerivative is `2.3`
* charge of `M` is `-1.1507`

I think at least one of these terms is the cause of the bias in the force.

**Comment by gmedders** [comment]
Thanks for the really detailed analysis. Just a few questions:

  * Can you just confirm the indices for the detailed force decomposition so that I can also explore? Is it i=0, j=3, with s corresponding to the first hydrogen of the molecule (H1, as you said)?
  * Could you also add rr1I_screen to the list of forces? And are all the forces from the previous comment on this issue in kcal/mol/A?

Thanks!

**Comment by zonca** [comment]
* yes, indices are right
* `rr1I_screen` is `0` for same molecule, every force in this thread is `kcal/mol/A`, just be careful of the other printouts in https://github.com/paesanilab/mbpol_openmm_plugin/issues/40#issuecomment-72706994, those are in native OpenMM units.

**Comment by gmedders** [comment]
great, thanks
