### ISSUE TITLE
Run constant energy simulations on box of liquid water

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#49]
After we completed debugging of the Electrostatics PME forces with polarizability,
run a constant energy simulation with one of the 256 molecules test set.

**Comment by zonca** [comment]
better to run on `empedocles`

**Comment by zonca** [comment]
Simulation parameters:

* `H2O_1.pdb` 512 water molecules
* PME boxsize `24.83 A`
* Verlet integrator timestep `0.02 fs`
* velocities set randomly based on `300 K` temperature

simulation is half way through, wanted @gmedders and @fpaesani to check if results make sense.

![energy](https://cloud.githubusercontent.com/assets/383090/7639141/bd72ac28-fa2e-11e4-994c-f4c805b85197.png)
![temperature](https://cloud.githubusercontent.com/assets/383090/7639151/c137a002-fa2e-11e4-9160-2a5a045bc9f0.png)

**Comment by gmedders** [comment]
The energies don't look entirely unreasonable considering the simulation starts with a random distribution of velocities and is quite short (100fs), but the temperature is quite off. Should be around 300K but is around 650K. Do you know what is going on?

You can also use a larger timestep (I probably told you the wrong one, or we miscommunicated a factor of 10). I would change to 0.2 fs. Ideally we would have somewhere around 500,000 steps (100 ps with a timestep of 0.02fs) to look at the energy conservation. I'm not sure if that is feasible in the reference implementation.

Also, is it possible to increase the print frequency? I would naively guess that each step is so slow that you could dump the statistics every 5 steps (or every step?) and not affect performance.

**Comment by fpaesani** [comment]
hmmm... there is something wrong with the temperature...

**Comment by zonca** [comment]
ok, I'll do a test with a standard OpenMM force field to check the OpenMM configuration is correct.
