### ISSUE TITLE
Standard format for saving velocities to file

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#57]
I have mostly completed a script, called `run_mbpol`, that can run standard simulations from a configuration file, see #56 

Currently I save:

* a file with trajectory of all particles in `.pdb` format
* a file with global properties of the system, e.g. energy, volume, density and so on

@fpaesani was interested also in saving velocities.
I asked on the [OpenMM forum](https://simtk.org/forums/viewtopic.php?f=161&t=5654&sid=364e702c403eb521d673a40da01aeb27) if they had a standard format, but they do not.

@fpaesani , @gmedders , @agoetz do you have suggestions on a standard format for velocities used in other MD codes?

**Comment by agoetz** [comment]
@zonca I am not aware of a common standard, many codes use their own formats.

**Comment by zonca** [comment]
thanks, I decided to use `HDF5Reporter` already implemented in the `mdtraj` Python package:

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/reporters/hdf5reporter.py

I think this is what is more closely a "standard" in OpenMM
