### ISSUE TITLE
Support ions in MBPol Dispersion force, Reference platform

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#64]
@pushpbajaj can you please post here the parameters for Cl-?

**Comment by pushpbajaj** [comment]
Dispersion parameters for H2O-Cl-

C6_ClH =  2.054967304401717e+02  kcal/mol * A^6
C6_ClO =  1.090054616587679e+03  kcal/mol * A^6
d6_ClH =  5.778854012725382e+00  A^(-1)   //2B fit cut off 3.5-5.5A latest training set.
d6_ClO =  1.638868407461115e+01  A^(-1)

**Comment by pushpbajaj** [comment]
Test case: 

Dimer: 
```
O       6.028800000e+00  -4.021520000e+00   1.384500000e+00
H       5.895700000e+00  -3.282780000e+00   7.820000000e-01
H       6.859700000e+00  -4.452620000e+00   1.204600000e+00
Cl      5.004300000e+00  -1.784700000e+00   3.409400000e+00
```

Dispersion energy = -1.306409202e+00 kcal/mol
```
Units are kcal/mol/A
Force on atom 1   6.305252015e-01    -1.376643613e+00    -1.246218136e+00
Force on atom 2   1.121793460e-01    -1.885277481e-01    -3.306484336e-01
Force on atom 3   4.044214508e-02    -5.815263969e-02    -4.805801523e-02
Force on atom 4  -7.831466926e-01     1.623324000e+00     1.624924585e+00

```

**Comment by zonca** [comment]
@sqamara once you are done with the same-water exclusions can you also:

* add `Cl` parameters to the xml definition (need to convert units)
* run the example of 1 water molecule plus an ion and check that it works
* create a test case based on `OpenMM` Python unit tests in  `openmm/wrappers/python/tests`

**Comment by sqamara** [comment]
Good morning Andrea,

I am working on writing the integration testers for mbpol.xml and I am
getting an error when I set the nonbondedMethod = app.CutoffPeriodic. 
This is illegal for the electrostatics force.  The cpp code manual sets
the nonbondedMethod to PME.  How would I emulate this in the python code?

Sebastian

**Comment by zonca** [comment]
When you detect PME, you can replace it with CutoffPeriodic.

**Comment by zonca** [comment]
implementation almost completed in #67 , all the parameters are already in the XML
