### ISSUE TITLE
Support ions in MBPol TwoBody force, Reference platform

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#68]
@pushpbajaj can you provide the polynomials for the 2 body force?

see this code for water:
https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/platforms/reference/src/MBPolReferenceTwoBodyForce.cpp#L150

in particular line 210 with the polynomial (from external file), down to 292.

Can you please paste on <http://gist.github.com> the equivalent for Chloride?

can you also specify what parameters are going to change for other ions?

Thanks!

TODO:

- [x] implement test with 2 waters and 1 Cl

**Comment by pushpbajaj** [comment]
@zonca 

https://gist.github.com/pushpbajaj/c55501bf5be340d98b1b

This contains the polynomials and also the polynomial evaluation code. 
The number of monomials, the number of non-linear parameters and the number of polynomials, the number of linear parameters is different for water-chloride than water. 

For the different monovalent ions (like sodium, potassium, chloride, iodide etc) the form of the monomials and polynomials will be the same but the linear and non-linear parameters will change depending on the fit. 

I think you can go ahead and set up everything for chloride right now. The change to make it general for ions will essentially be changing names and numbers. It will be very straightforward.

**Comment by zonca** [comment]
thanks @pushpbajaj , can you also provide a test case?
the best would be 1 water molecule (the first of water3) and then 1 Chloride, any position is fine.

**Comment by zonca** [comment]
@pushpbajaj  can you specify that are the variable names in the code for linear and nonlinear parameters?

**Comment by pushpbajaj** [comment]
@zonca I updated the gist page with the latest fits and also added `x2b-h2o-cl-dispersion.cpp` which contains the two non-linear parameters used in dispersion. 

The non-linear parameters are:

```
const double x2b_h2o_cl_v2x::k_HH_intra = 1.518249331817580e+00; // A^(-1)
const double x2b_h2o_cl_v2x::k_OH_intra = 1.999999994829699e+00; // A^(-1)

const double x2b_h2o_cl_v2x::k_ClH_coul = 3.972792180981702e-01; // A^(-1)
const double x2b_h2o_cl_v2x::k_ClO_coul = 3.462704545202026e-01; // A^(-1)

const double x2b_h2o_cl_v2x::k_cllp_main = 9.383324153811023e-01; // A^(-1)

const double x2b_h2o_cl_v2x::in_plane_gamma = 2.125481530694774e-01;
const double x2b_h2o_cl_v2x::out_of_plane_gamma = 1.673153512145568e-01;
```

And two more used in dispersion:
```
const double x2b_h2o_cl_dispersion::d6_ClH = 1.631899730583967e+01; // A^(-1)
const double x2b_h2o_cl_dispersion::d6_ClO = 2.606978398421525e+01; // A^(-1)
```

The linear parameters (coefficients for the polynomials) are in `x2b-h2o-cl-fit-params.h`.

**Comment by pushpbajaj** [comment]
@zonca Here is a test case for the 2B polynomial part 

I'm using the same dimer as I used for the dispersion test case, let me know if you need another configuration. 

H2O-Cl-
```
O       6.028800000e+00  -4.021520000e+00   1.384500000e+00
H       5.895700000e+00  -3.282780000e+00   7.820000000e-01
H       6.859700000e+00  -4.452620000e+00   1.204600000e+00
Cl      5.004300000e+00  -1.784700000e+00   3.409400000e+00
```

2B polynomial energy = 2.027705104e+00 kcal/mol

2B polynomial gradients: 
```
Atom 1 -3.278090251e+00  4.781931804e+00  2.443283214e+00 
Atom 2  5.700852530e-01 -1.298619977e+00  1.232417788e+00 
Atom 3  2.181168186e-01  1.161499952e+00  5.698707152e-01 
Atom 4  2.489888179e+00 -4.644811779e+00 -4.245571717e+00 
```

**Comment by zonca** [comment]
thanks @pushpbajaj , can you also prepare a test case of 2 water molecules + Cl? so we can test water-water and water-ion in the same test case.

**Comment by sqamara** [comment]
@pushpbajaj , I've implemented one water and one Cl, and the test is passing.  Could I have the test case for 2 waters and one Cl?

**Comment by pushpbajaj** [comment]
@sqamara @zonca Here is a test case with 2 waters and 1 Cl

For this configuration:
```
O1         0.2071123419        0.1431350648        0.2575948809
H1         0.3968154394       -0.4466985822       -0.5164780569
H1        -0.0790971024        0.9461358941       -0.1868734592
O2         3.1469464639        0.2657051814       -0.5347590767
H2         2.3878654247        0.3762497422        0.0532565299
H2         2.7252172819       -0.2612759028       -1.2421153352
Cl         1.0072476456       -1.3374671605       -2.3154322027
```

Total 2B polynomial energy = 19.6295 kcal/mol
The individual contributions are: 
water1-cl 2B polynomial energy = 10.8732 
water2-cl                                     = 6.07145
water1-water2                             = 2.68486

**Comment by zonca** [comment]
Great, thanks, @sqamara can you add this to the unit tests?

**Comment by zonca** [comment]
@sqamara added checklist to track completion of this

**Comment by sqamara** [comment]
@zonca  implementing test with 2 waters and 1 was completed and merged here Clhttps://github.com/paesanilab/mbpol_openmm_plugin/pull/76

**Comment by zonca** [comment]
ok, good, so I am closing this.
