### ISSUE TITLE
H2O-Cl- Dispersion: change of damping parameters (new fit) 

### ISSUE THREAD

**Issue by pushpbajaj** [paesanilab/mbpol_openmm_plugin#69]
@zonca 

Please update the d6 parameters for water-chloride to these: 

```
const double x2b_h2o_cl_dispersion::d6_ClH = 1.631899730583967e+01; // A^(-1)
const double x2b_h2o_cl_dispersion::d6_ClO = 2.606978398421525e+01; // A^(-1)
```

Please also mention in the code as a comment that these correspond to this fit:

`vqz-f12-CP-fit-3.5-5.5-new-polar-5th-iteration+scans`

Now, with these parameters, for this configuration: 
```
O       6.028800000e+00  -4.021520000e+00   1.384500000e+00
H       5.895700000e+00  -3.282780000e+00   7.820000000e-01
H       6.859700000e+00  -4.452620000e+00   1.204600000e+00
Cl      5.004300000e+00  -1.784700000e+00   3.409400000e+00
```

The dispersion energy is -1.306598 kcal/mol

**Comment by zonca** [comment]
@sqamara, can you update this in the code? please add "close issue #69" to the commit message so we have a reference to this.

**Comment by zonca** [comment]
completed, need only to merge the pull request
