### ISSUE TITLE
Segmentation fault 

### ISSUE THREAD

**Issue by JNapoli** [paesanilab/mbpol_openmm_plugin#71]
Hi @zonca,

I'd like to run mbpol in OpenMM, but the provided water14.py example segfaults when I try running it. I have installed both OpenMM and the mbpol plugin with conda; I have confirmed that the segfault occurs for mbpol but not for tip4pfb; I have also confirmed that it occurs at the simulation creation step. Can you reproduce this error or know of a fix to the script that I am overlooking? Thank you!

-Joe

**Comment by zonca** [comment]
@JNapoli thanks for reporting this! I just noticed OpenMM updated the conda package to 6.3.0, haven't had time yet to rebuild mbpol.

In the meantime, can you try install OpenMM 6.2 with:

    conda install -c https://conda.binstar.org/omnia openmm=6.2.0

**Comment by JNapoli** [comment]
I get an exception after installing v6.2.0:

"""
Exception: Specified a Platform for a Context which does not support all required kernels
"""

This also happens for mbpol and not for tip4pfb.

**Comment by zonca** [comment]
I tested right now on a machine here and it works.
can you try removing mbpol and installing it again?

**Comment by JNapoli** [comment]
I get the same exception:

```
jnapoli@node016 ~/reax/mbpol_github_example >> python -c 'from simtk import openmm; print(openmm.version.short_version)'
6.2.0
jnapoli@node016 ~/reax/mbpol_github_example >> conda install -c https://conda.binstar.org/paesanilab mbpol
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /home/jnapoli/install/anaconda:

The following NEW packages will be INSTALLED:

    mbpol: 1.0.1-py27_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#######################################################################################################################################################################| 100%
jnapoli@node016 ~/reax/mbpol_github_example >> python -c 'import mbpol'
jnapoli@node016 ~/reax/mbpol_github_example >> python water14.py
Traceback (most recent call last):
  File "water14.py", line 43, in <module>
    simulation = app.Simulation(pdb.topology, system, integrator, platform)
  File "/home/jnapoli/install/anaconda/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 77, in __init__
    self.context = mm.Context(system, integrator, platform)
  File "/home/jnapoli/install/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 15302, in __init__
    this = _openmm.new_Context(*args)
Exception: Specified a Platform for a Context which does not support all required kernels
jnapoli@node016 ~/reax/mbpol_github_example >>
```

**Comment by zonca** [comment]
Unfortunately I cannot reproduce this issue in any of my systems.

I recommend you try to build the plugin from source, using 1.0.1: https://github.com/paesanilab/mbpol_openmm_plugin/releases/tag/v1.0.1, make sure you use OpenMM 6.2

**Comment by JNapoli** [comment]
Thanks for your help. I have it working with OpenMM v6.2 and mbpol compiled from source.

**Comment by zonca** [comment]
ok, that is good news, I'll ping you when I get the conda package working
with 6.3 so you can give that a try.
