### ISSUE TITLE
Build conda package for OpenMM 6.3

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#72]
Need to update the coda package on https://conda.binstar.org/paesanilab from building against 6.2 to build against 6.3.

**Comment by zonca** [comment]
@sqamara, I fixed the plugin for OpenMM 6.3, so now `master` runs Travis tests with OpenMM 6.3.
Just FYI, in your branch you can still test with 6.2, we'll fix it when we merge branches.

**Comment by zonca** [comment]
@jnapoli I just built new conda packages for MBPol with support for OpenMM 6.3, would you mind testing those on your machine? I am not positive they'll work, as I didn't understand your previous problem, but it would be useful to test.

See new install instructions:
https://github.com/paesanilab/mbpol_openmm_plugin/blob/master/INSTALL.md

**Comment by JNapoli** [comment]
@zonca, it works for me with OpenMM v6.3 now, but only after building mbpol from source. Installing via conda did not work for me, though I may have made an error.

**Comment by zonca** [comment]
ok, thanks for testing

**Comment by zonca** [comment]
`conda` package built and updated install instructions. if we get more reports of issue we might need to dig deeper and try to understand what is going on, but for now I am closing
