### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by agoetz** [paesanilab/mbpol_openmm_plugin#90]
@zonca I fail to install the mbpol_openmm_plugin on my macbook, following the instructions in INSTALL.md

To configure I first had to edit CMakeCache.txt and set MBPOL_BUILD_OPENCL_LIB:BOOL=OFF

I also could not find OPENMM_MAJOR_VERSION and OPENMM_MINOR_VERSION in the ccmake menu, I am not sure if this matters.

After configuration, the compilation fails

[ 40%] Building CXX object platforms/reference/CMakeFiles/OpenMMMBPolReference.dir/src/MBPolReferenceKernels.cpp.o
/Users/andi/software/MBpol/mbpol_openmm_plugin-1.0.0/platforms/reference/src/MBPolReferenceKernels.cpp:414:5: error: 
      no matching function for call to 'computeNeighborListVoxelHash'
    computeNeighborListVoxelHash( _neighborList, numParticles, posData, allExclusions, extractBoxSize(...
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/openmm/include/openmm/reference/ReferenceNeighborList.h:35:20: note: candidate function not viable:
      no known conversion from 'OpenMM::RealVec' to 'const OpenMM::RealVec *' for 5th argument; take the
      address of the argument with &
void OPENMM_EXPORT computeNeighborListVoxelHash(
                   ^
/Users/andi/software/MBpol/mbpol_openmm_plugin-1.0.0/platforms/reference/src/MBPolReferenceKernels.cpp:579:5: error: 
      no matching function for call to 'computeNeighborListVoxelHash'
    computeNeighborListVoxelHash( *neighborList, numParticles, allPosData, allExclusions, extractBoxSi...
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/openmm/include/openmm/reference/ReferenceNeighborList.h:35:20: note: candidate function not viable:
      no known conversion from 'OpenMM::RealVec' to 'const OpenMM::RealVec *' for 5th argument; take the
      address of the argument with &
void OPENMM_EXPORT computeNeighborListVoxelHash(
                   ^
2 errors generated.
make[2]: *_\* [platforms/reference/CMakeFiles/OpenMMMBPolReference.dir/src/MBPolReferenceKernels.cpp.o] Error 1
make[1]: **\* [platforms/reference/CMakeFiles/OpenMMMBPolReference.dir/all] Error 2
make: **\* [all] Error 2

**Comment by zonca** [comment]
I think you tried to install 1.0.0 but that does not support open mm 6.3
You should try with 1.0.2,
For some reason it was hidden before now I made it more prominent, my bad.

**Comment by agoetz** [comment]
Yes, version 1.0.0. That was the only one I saw so did not mention the version numbers. I will try again with 1.0.2. Thanks.

**Comment by agoetz** [comment]
Version 1.0.2 works.

You should disable OPENCL. I switched it off manually during the cmake configuration. But initially it comes up with an error

 CMake Error at CMakeLists.txt:97 (ADD_SUBDIRECTORY):
   add_subdirectory given source "platforms/opencl" which is not an existing
   directory.
