### ISSUE TITLE
Pass thole parameters for Electrostatics in the XML

### ISSUE THREAD

**Issue by zonca** [paesanilab/mbpol_openmm_plugin#94]
Currently the C++ interface has support for changing the thole parameters with the `setTholeParameters` method, we should modify the Python parses so that Tholes are defined in the XML and set inside `mbpol.py`.

**Comment by zonca** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;GCgrpl6Z&#x2F;21-cuda-electrostatics"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> CUDA electrostatics</a>

**Comment by sqamara** [comment]
It looks like they are already introduced in the xml with the residue of the electrostatics 
`<Residue name="HOH" class1="O" class2="H" class3="H" thole-charge-charge="0.4" thole-charg    e-dipole="0.4" thole-dipole-dipole-intermolecules="0.055" thole-dipole-dipole-OH="0.626" thole-dip    ole-dipole-HH="0.055"/>`

**Comment by zonca** [comment]
@sqamara they are not actually water-specific, so better move them to the global parameters, about the names, I would use:

* thole-charge-charge
* thole-charge-dipole
* thole-dipole-dipole
* thole-dipole-dipole-singlebond

Let's ask what is the best naming scheme at the lab on Wednesday

**Comment by sqamara** [comment]
addressed in https://github.com/paesanilab/mbpol_openmm_plugin/commit/341216ab4751667c0c51deba07bde6547099f332

**Comment by zonca** [comment]
@sqamara in the C++ we use 5 thole parameters,
so we should repeat the `thole-dipole-dipole` also as the last element
